variables:
  ARTIFACTS_DIR: "/builds/macallen2022/Vue3"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
- build vue
- test vue
- deploy vue

build:
  image: node:16-alpine
  stage: build vue
  environment:
    name: nodejs    
  script:
    - echo $JOB_ID
    - echo "$CI_JOB_STAGE"    
    - yarn install        
    - yarn build    
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - $ARTIFACTS_DIR
      
test:
  image: ubuntu:latest
  stage: test vue
  environment: 
    name: ubuntu
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - venv/
  script:
    - echo $JOB_ID
    - echo "$CI_JOB_STAGE"        
    - echo $CI_PROJECT_DIR
    - apt-get update
    - apt-get install sudo
    - apt -y update
    - apt-get upgrade -y
    - apt-get install -y curl
    - curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
    - apt-get install -y nodejs         
    - whereis npm
    - /usr/bin/npm -v
   
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - $ARTIFACTS_DIR

deploy production:
  stage: deploy vue
  environment:
    name: heruko
  when: manual
  script: 
    -echo $JOB_ID
